ignore:
  - 'input.yaml$'
  - 'README\.md$'
  - '\.pathogen\.yml$'
variables:
  - name: firstName
    description: the first name of a person
    value: Moe
  - name: lastName
    description: the last name of a person
    value: Howard
  - name: partners
    description: a comma separated list of partners for the person 
    value: Larry Fine,Curly Howard
