before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    main: ./cmd/pathogen.go
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
